name: Add Numbers

on:
  workflow_dispatch:
    inputs:
      number1:
        description: 'First number'
        required: true
        type: number
      number2:
        description: 'Second number'
        required: true
        type: number

jobs:
  add:
    runs-on: ubuntu-latest
    outputs:
      sum: ${{ steps.calculate.outputs.sum }}
    steps:
      - name: Calculate sum
        id: calculate
        run: |
          sum=$(( ${{ inputs.number1 }} + ${{ inputs.number2 }} ))
          echo "sum=$sum" >> $GITHUB_OUTPUT
          echo "The sum of ${{ inputs.number1 }} and ${{ inputs.number2 }} is $sum" 