name: Random Number Generator

on:
  workflow_dispatch:
    inputs:
      max_number:
        description: 'Maximum number for random generation'
        required: true
        type: number
        default: 100
  workflow_call:
    inputs:
      max_number:
        description: 'Maximum number for random generation'
        required: true
        type: number
        default: 100

jobs:
  random:
    runs-on: ubuntu-latest
    steps:
      - name: Generate random number
        id: generate
        run: |
          number=$(( $RANDOM % ${{ inputs.max_number }} + 1 ))
          echo "RANDOM_NUMBER=$number" >> $GITHUB_ENV
          echo "Generated random number: $number" 